name: 'TypeScript Action Recipe'
description: 'Waites for some milliseconds, writes an awesome job summary to the workflow output and returns the current date and time.'
author: 'Michael Kaufmann'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
